# Report Descriptor and some constants
# todo: import & use constants in main code 

IPRODUCT             = const(0x01) # str ref
ISERIAL              = const(0x02) 
IMANUFACTURER        = const(0x03)
IDEVICECHEMISTRY     = const(0x04)
IOEMVENDOR           = const(0x05)

HID_PD_IPRODUCT            = const(0x01) # FEATURE ONLY
HID_PD_SERIAL              = const(0x02) # FEATURE ONLY
HID_PD_MANUFACTURER        = const(0x03) # FEATURE ONLY

HID_PD_RECHARGEABLE        = const(0x06) # FEATURE ONLY
HID_PD_PRESENTSTATUS       = const(0x07) # INPUT OR FEATURE(required by Windows)
HID_PD_REMAINTIMELIMIT     = const(0x08)
HID_PD_MANUFACTUREDATE     = const(0x09)
HID_PD_CONFIGVOLTAGE       = const(0x0A) # 10 FEATURE ONLY
HID_PD_VOLTAGE             = const(0x0B) # 11 INPUT (NA) OR FEATURE(implemented)
HID_PD_REMAININGCAPACITY   = const(0x0C) # 12 INPUT OR FEATURE(required by Windows)
HID_PD_RUNTIMETOEMPTY      = const(0x0D) 
HID_PD_FULLCHRGECAPACITY   = const(0x0E) # 14 FEATURE ONLY. Last Full Charge Capacity 
HID_PD_WARNCAPACITYLIMIT   = const(0x0F)
HID_PD_CPCTYGRANULARITY1   = const(0x10)
HID_PD_REMNCAPACITYLIMIT   = const(0x11)
HID_PD_DELAYBE4SHUTDOWN    = const(0x12) # 18 FEATURE ONLY
HID_PD_DELAYBE4REBOOT      = const(0x13)
HID_PD_AUDIBLEALARMCTRL    = const(0x14) # 20 INPUT OR FEATURE
HID_PD_CURRENT             = const(0x15) # 21 FEATURE ONLY
HID_PD_CAPACITYMODE        = const(0x16)
HID_PD_DESIGNCAPACITY      = const(0x17)
HID_PD_CPCTYGRANULARITY2   = const(0x18)
HID_PD_AVERAGETIME2FULL    = const(0x1A)
HID_PD_AVERAGECURRENT      = const(0x1B)
HID_PD_AVERAGETIME2EMPTY   = const(0x1C)

HID_PD_IDEVICECHEMISTRY    = const(0x1F) # Feature
HID_PD_IOEMINFORMATION     = const(0x20) # Feature

# HID Report Descriptor for a USB UPS Power Device
# fmt: off
_UPS_REPORT_DESC = (
b'\x05\x84'                         # USAGE_PAGE (Power Device)
b'\x09\x04'                         # USAGE (UPS)
b'\xA1\x01'                         # COLLECTION (Application)
b'\x09\x24'                         #   USAGE (Sink)
b'\xA1\x02'                         #   COLLECTION (Logical)
b'\x75\x08'                         #     REPORT_SIZE (8)
b'\x95\x01'                         #     REPORT_COUNT (1)
b'\x15\x00'                         #     LOGICAL_MINIMUM (0)
b'\x26\xFF\x00'                     #     LOGICAL_MAXIMUM (255)
b'\x85\x01'     #     REPORT_ID (1)
b'\x09\xFE'                         #     USAGE (iProduct)
b'\x79\x02'                         #     STRING INDEX (2)
b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
b'\x85\x02'     #     REPORT_ID (2)
b'\x09\xFF'                         #     USAGE (iSerialNumber)
b'\x79\x03'                         #  STRING INDEX (3)
b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
b'\x85\x03'     #     REPORT_ID (3)
b'\x09\xFD'                         #     USAGE (iManufacturer)
b'\x79\x01'                         #     STRING INDEX (1)
b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
b'\x05\x85'                         #     USAGE_PAGE (Battery System) ====================
b'\x85\x06'     #     REPORT_ID (6)
b'\x09\x8B'                         #     USAGE (Rechargable)                  
b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
b'\x85\x1F'     #     REPORT_ID (31)
b'\x09\x89'                         #     USAGE (iDeviceChemistry)
b'\x79\x04'                         #     STRING INDEX (4)
b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
#b'\x85\x20'     #     REPORT_ID (32)
#b'\x09\x8F'                         #     USAGE (iOEMInformation)
#b'\x79\x05'                         #     STRING INDEX (5)
#b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
b'\x85\x16'     #     REPORT_ID (22)
b'\x09\x2C'                         #     USAGE (CapacityMode)
b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
b'\x85\x10'     #     REPORT_ID (16)
b'\x09\x8D'                         #     USAGE (CapacityGranularity1)
b'\x26\x64\x00'                    #     LOGICAL_MAXIMUM (100)
#b'\x25\x64'
b'\xB1\x22'                         #     FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
#b'\x09\x8D'                         #     USAGE (CapacityGranularity1)
#b'\x81\x22'                         #     INPUT (d)
b'\x85\x18'     #     REPORT_ID (24)
b'\x09\x8E'                         #     USAGE (CapacityGranularity2)
b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
#b'\x09\x8E'                        #     USAGE (CapacityGranularity2)
#b'\x81\x23'                        #     INPUT ()
b'\x85\x0E'     #     REPORT_ID (14)        
b'\x09\x67'                         #     USAGE (FullChargeCapacity)
b'\xB1\x83'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x85\x17'     #     REPORT_ID (23)
b'\x09\x83'                         #     USAGE (DesignCapacity)
b'\xB1\x83'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
#b'\x09\x83'                        #     USAGE (DesignCapacity)
#b'\x81\x83'                        #     INPUT ()
b'\x85\x0C'     #     REPORT_ID (12)
b'\x09\x66'                         #     USAGE (RemainingCapacity)
b'\x81\xA3'                         #     INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x66'                         #     USAGE (RemainingCapacity)
b'\xB1\xA3'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x85\x0F'     #     REPORT_ID (15)
b'\x09\x8C'                         #     USAGE (WarningCapacityLimit)
b'\xB1\xA2'                         #     FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
#b'\x09\x8C'                         #     USAGE (WarningCapacityLimit)
#b'\x81\xA2'                         #     INPUT ()
b'\x85\x11'     #     REPORT_ID (17)
b'\x09\x29'                         #     USAGE (RemainingCapacityLimit)
b'\xB1\xA2'                         #     FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x85\x09'     #     REPORT_ID (9)
b'\x09\x85'                         #     USAGE (ManufacturerDate)
b'\x75\x10'                         #     REPORT_SIZE (16)
b'\x27\xFF\xFF\x00\x00'             #     LOGICAL_MAXIMUM (65534)
b'\xB1\xA3'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x85\x1A'     #     REPORT_ID (26)
b'\x09\x6A'                         #     USAGE (AverageTimeToFull)
b'\x27\xFF\xFF\x00\x00'             #     LOGICAL_MAXIMUM (65534)
b'\x66\x01\x10'                     #     UNIT (Seconds)
b'\x55\x00'                         #     UNIT_EXPONENT (0)
b'\xB1\xA3'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield) 
b'\x85\x1C'      #     REPORT_ID (28)
b'\x09\x69'                         #     USAGE (AverageTimeToEmpty)  
b'\x81\xA3'                         #     INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x69'                         #     USAGE (AverageTimeToEmpty)
b'\xB1\xA3'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x85\x0D'     #     REPORT_ID (13)    
b'\x09\x68'                         #     USAGE (RunTimeToEmpty)  
b'\x81\xA3'                         #     INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x68'                         #     USAGE (RunTimeToEmpty)
b'\xB1\xA3'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)      
b'\x85\x08'     #     REPORT_ID (8)
b'\x09\x2A'                         #     USAGE (RemainingTimeLimit)
b'\x75\x10'                         #     REPORT_SIZE (16)
b'\x27\x64\x05\x00\x00'             #     LOGICAL_MAXIMUM (1380)
b'\x16\x78\x00'                     #     LOGICAL_MINIMUM (120)
b'\x81\x22'                         #     INPUT (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x2A'                         #     USAGE (RemainingTimeLimit)
b'\xB1\xA2'                         #     FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x05\x84'                         #     USAGE_PAGE (Power Device) ====================
b'\x85\x12'      #     REPORT_ID (18)
b'\x09\x57'                         #     USAGE (DelayBeforeShutdown)
b'\x16\x00\x80'                     #     LOGICAL_MINIMUM (-32768)
b'\x27\xFF\x7F\x00\x00'             #     LOGICAL_MAXIMUM (32767)
b'\xB1\xA2'                         #     FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x85\x13'     #     REPORT_ID (19)
b'\x09\x55'                         #     USAGE (DelayBeforeReboot)
b'\xB1\xA2'                         #     FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x85\x0A'     #     REPORT_ID (10)
b'\x09\x40'                         #     USAGE (ConfigVoltage)
b'\x15\x00'                         #     LOGICAL_MINIMUM (0)
b'\x27\xFF\xFF\x00\x00'             #     LOGICAL_MAXIMUM (65535)
b'\x67\x21\xD1\xF0\x00'             #     UNIT (Centivolts)
b'\x55\x05'                         #     UNIT_EXPONENT (5)
b'\xB1\x23'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Nonvolatile' Bitfield)
b'\x85\x0B'     #     REPORT_ID (11)
b'\x09\x30'                         #     USAGE (Voltage)
b'\x81\xA3'                         #     INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x30'                         #     USAGE (Voltage)
b'\xB1\xA3'                         #     FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x85\x14'     #     REPORT_ID (20)
b'\x09\x5A'                         #     USAGE (AudibleAlarmControl)
b'\x75\x08'                         #     REPORT_SIZE (8)
b'\x15\x01'                         #     LOGICAL_MINIMUM (1)
b'\x25\x03'                         #     LOGICAL_MAXIMUM (3)
b'\x65\x00'                         #     UNIT (0)
b'\x55\x00'                         #     UNIT_EXPONENT (0)
b'\x81\x22'                         #     INPUT (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x5A'                         #     USAGE (AudibleAlarmControl)
b'\xB1\xA2'                         #     FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x02'                         #     USAGE (PresentStatus)
b'\xA1\x02'                         #     COLLECTION (Logical)
b'\x85\x07'     #       REPORT_ID (7)
b'\x05\x85'                         #       USAGE_PAGE (Battery System) =================
b'\x09\x44'                         #       USAGE (Charging)
b'\x75\x01'                         #       REPORT_SIZE (1)
b'\x15\x00'                         #       LOGICAL_MINIMUM (0)
b'\x25\x01'                         #       LOGICAL_MAXIMUM (1)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x44'                         #       USAGE (Charging)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x45'                         #       USAGE (Discharging)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x45'                         #       USAGE (Discharging)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\xD0'                         #       USAGE (ACPresent)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\xD0'                         #       USAGE (ACPresent)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\xD1'                         #       USAGE (BatteryPresent)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\xD1'                         #       USAGE (BatteryPresent)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x42'                         #       USAGE (BelowRemainingCapacityLimit)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x42'                         #       USAGE (BelowRemainingCapacityLimit)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x43'                         #       USAGE (RemainingTimeLimitExpired)
b'\x81\xA2'                         #       INPUT (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x43'                         #       USAGE (RemainingTimeLimitExpired)
b'\xB1\xA2'                         #       FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)  
b'\x09\x4B'                         #       USAGE (NeedReplacement)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x4B'                         #       USAGE (NeedReplacement)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)    
b'\x09\xDB'                         #       USAGE (VoltageNotRegulated)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\xDB'                         #       USAGE (VoltageNotRegulated)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x46'                         #       USAGE (FullyCharged)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x46'                         #       USAGE (FullyCharged)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x47'                         #       USAGE (FullyDischarged)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x47'                         #       USAGE (FullyDischarged)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)    
b'\x05\x84'                         #       USAGE_PAGE (Power Device) =================
b'\x09\x68'                         #       USAGE (ShutdownRequested)
b'\x81\xA2'                         #       INPUT (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x68'                         #       USAGE (ShutdownRequested)
b'\xB1\xA2'                         #       FEATURE (Data' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x69'                         #       USAGE (ShutdownImminent)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x69'                         #       USAGE (ShutdownImminent)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x73'                         #       USAGE (CommunicationLost)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x73'                         #       USAGE (CommunicationLost)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x09\x65'                         #       USAGE (Overload)
b'\x81\xA3'                         #       INPUT (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Bitfield)
b'\x09\x65'                         #       USAGE (Overload)
b'\xB1\xA3'                         #       FEATURE (Constant' Variable' Absolute' No Wrap' Linear' No Preferred' No Null Position' Volatile' Bitfield)
b'\x95\x02'                         #       REPORT_COUNT (2) # padding bits to make the report byte aligned
b'\x81\x01'                         #       INPUT (Constant' Array' Absolute)
b'\xB1\x01'                         #       FEATURE (Constant' Array' Absolute' No Wrap' Linear' Preferred State' No Null Position' Nonvolatile' Bitfield)
b'\xC0'                     #     END_COLLECTION
b'\xC0'                 #   END_COLLECTION
b'\xC0'             # END_COLLECTION
)

